### ISSUE TITLE
это не REST

### ISSUE THREAD

**Issue by tksasha** [ildarusmanov/imgloader#3]
https://github.com/ildarusmanov/imgloader/blob/918f10fc80a33492217581968145a4c228065d1a/config/routes.rb#L4

**Comment by ildarusmanov** [comment]
у меня не было цели создавать RESTful приложение, т.к. в данном случае контроллер служит лишь доказательством того, что разработанная логика работает.

**Comment by ildarusmanov** [comment]
@tksasha fixed, take a look please
