### ISSUE TITLE
использовать один метод для обработки GET и POST запроса плохая практика и слишком усложняет код

### ISSUE THREAD

**Issue by tksasha** [ildarusmanov/imgloader#4]
https://github.com/ildarusmanov/imgloader/blob/918f10fc80a33492217581968145a4c228065d1a/app/controllers/home_controller.rb#L4

**Comment by ildarusmanov** [comment]
собственно туда же - https://github.com/ildarusmanov/imgloader/issues/5

**Comment by ildarusmanov** [comment]
@tksasha fixed, take a look please
