### ISSUE TITLE
слишком усложненный контролер

### ISSUE THREAD

**Issue by tksasha** [ildarusmanov/imgloader#5]
https://github.com/ildarusmanov/imgloader/blob/918f10fc80a33492217581968145a4c228065d1a/app/controllers/home_controller.rb#L1

Я бы написал следующее
```ruby
#
# POST /images
#
class ImagesController < ApplicationController
  before_action :build_resource, only: :create

  def create
    if resource.save
      redirect_to :images
    else
      render :new
    end
  end

  private
  def build_resource
    @resource = Images.new resource_params
  end

  def resource_params
    params.require(:images).permit(:url)
  end
end
```

где `Images` сервис-класс, в котором и будет инкапсулирована логика парсинга и сохранения изображений

**Comment by tksasha** [comment]
```ruby
class Images
  def initialize params={}
    @url = params[:url]
  end

  def save
    # 1. открываем запрашиваемый URL. Можно воспользоваться `open-uri`
    #
    # 2. парсим HTML и находим все изображения на нем. (Nokogiri CSS Selector)
    #
    # 3. проходимся по полученному массиву из ссылок на изображения и сохраняем их. (Лучше это делать в Background Jobs, чтобы добиться паралельности)
    #
  end
end
```

**Comment by ildarusmanov** [comment]
Cогласен с тем что сложный, я и не делал его простым, т.к. полагал,что важнее реализация того, что внутри, а это только фасад. К тому же REST и HTTP не панацея.

Собственно если делать контроллер нормально, то тогда нужно будет добавлять еще контроллер для отображения списка изображений по /sourcelinks/:id/images, и будет два контроллера SourcelinksController и ImagesController, и в этом случае нужно будет еще хранить это все в БД. 

И тогда будет примерно так в роутах:
```
resources :sourcelinks, only: [:index, :new, :create] do
  resources :images, only: [:index, :show]
end
```
А добавлять источник через контроллер изображений плохая идея, это же разные ресурсы.

**Comment by ildarusmanov** [comment]
@tksasha fixed, take a look please
